### ISSUE TITLE
buoy programs that may drift in the MIZ

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/meta_overview_sea_ice_available_data#4]

**Comment by danielmwatkins** [comment]
Are you only looking for drift data with coincident wave measurements? If not, the MOSAiC drift data is now available on the Arctic Data Center, and many of the buoys drifted into the MIZ.

**Comment by jerabaul29** [comment]
Many thanks for pointing this out. This is definitely part of the kind of data I am interested in keeping track of. After a quick search there I found:

- https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2KP7TS83
- https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2WW77163
- https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2JD4PQ7V

Anything more you can think of? :) I will definitely add it to the overview summary :) .

**Comment by danielmwatkins** [comment]
Yes, those three links are for the same project and that's the data I was talking about. We just got the acceptance notification for the data paper, which will be in Nature Scientific Data, so when the article comes out that would be a good umbrella reference for it, with the links to the processed data and code.

Another one to look into is the Norwegian Young Ice Cruise (N-ICE 2015). I know that wave buoys were included in the deployment, though I can't say for sure that the wave data is available. Drift tracks and many other measurements are available at https://www.npolar.no/en/projects/n-ice2015/#toggle-project-dataset

**Comment by jerabaul29** [comment]
Congratulations on your accepted paper :) .

I have added both, many thanks for pointing these out, and feel free to comment if you see anything that should be changed. Closing this issue for now (if comments on how I added the references to these feel free to re-open / comment), and if you have more datasets you can think about that should be added in the future, please let me know :) .
